config/routes.rb
Pushertest::Application.routes.draw do
  devise_for :users

  root :to => "messages#index"

  resources :messages, :only => [:create]
  post 'pusher/auth', :to => "pusher#auth"

  get 'game/playsnake', :to => "game#play_snake"
  get 'game/playasteroids', :to => "game#play_asteroids"
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :user_id

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/game_controller.rb
class GameController < ApplicationController

  def play_snake
  end

  def play_asteroids
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :authenticate_user!

  require 'pusher'

  Pusher.app_id = '49030'
  Pusher.key = '942f40662c8b1236e58b'
  Pusher.secret = '7f12a2427ce3be7e66cb'

  def create
    @message = current_user.messages.build(params[:message])
    Pusher['presence-channel'].trigger('my-event', {:message => @message.content, :name => current_user.email})
    @message.save!
    render :json => @message
  end

  def index
    @messages = Message.where(created_at: (current_user.current_sign_in_at..Time.now))
  end

end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController

  protect_from_forgery :except => :auth # stop rails CSRF protection for this action

  def auth
    if current_user
      response = Pusher[params[:channel_name]].authenticate(params[:socket_id], {
        :user_id => current_user.id, # => required
        :user_info => {
          :email => current_user.email
        }
      })
      render :json => response
    else
      render :text => "Forbidden", :status => '403'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pusher_helper.rb
module PusherHelper
end

app/views/game/play_asteroids.html.erb
<%= javascript_include_tag "asteroids/asteroids", "asteroids/app" %>
<%= stylesheet_link_tag "game_asteroids", :media => "all" %>

<div id="game"></div>

<div id="console"></div>

app/views/game/play_snake.html.erb
<%= javascript_include_tag "game_snake" %>
<%= stylesheet_link_tag "game_snake", :media => "all" %>

<h1>Snake</h1>
<div id="container">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pushertest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script src="http://js.pusher.com/2.1/pusher.min.js"></script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <% if current_user %>
    <p>
      </em>Welcome, <%= current_user.email %>!</em>
      <%= link_to "Logout", destroy_user_session_url, :method => :delete %>
    </p>
  <% end %>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/messages/_message.html.erb
<li>
  <span class="time"><%= message.created_at.strftime("%H:%M") %></span>
  <span class="sender <%= "self" if message.user.email == current_user.email %>">
    <%= message.user.email %>:
  </span>
  <span class="msg"><%= message.content %></span>
</li>

app/views/messages/index.html.erb
<script id="current_user" type="text/json">
  <%= current_user.email %>
</script>

<div id="chatbox">
  <h3>Chat Room</h3>
  <ul id="chat">
    <% if @messages.count <= 10 %>
      <%= render @messages %>
    <% else %>
      <%= render @messages[-10..-1] %>
    <% end %>
  </ul>

  <%= form_for Message.new, :remote => true do |f| %>
    <%= f.text_field :content %>
    <%= f.submit "Send" %>
  <% end %>
</div>

<div id="membersbox">
  <h3>Users Present</h3>
</div>

<div class="game-buttons">
  <h3>Play Games</h3>
  <%= button_to "Play Snake", game_playsnake_url, :method => "get" %>
  <%= button_to "Play Asteroids", game_playasteroids_url, :method => "get" %>
</div>